In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


### Tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many NN learn is that they start with tensors full of random numbers and then adjust those numbers to better represent data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [17]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0212, 0.4198, 0.9301, 0.0608],
        [0.0054, 0.4597, 0.9493, 0.4941],
        [0.7074, 0.7211, 0.7724, 0.9408]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channels
random_image_size_tensor.shape

torch.Size([224, 224, 3])

### Zeros and ones

In [20]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Create tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big issues you will run into with PyTorch
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [25]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32, # datatype
                               device=None,         # cpu vs cuda, tensors shall be on the same device
                               requires_grad=False)  # whethe or not to track radiance with these tensors
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [28]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

### Manipulating tensors (tensor operation)

Tensor operation include:
* addition
* subtraction
* multiplication (element-wise)
* division
* matrix multiplication (dot product)

In [29]:
# Create a tensor and use addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [30]:
# Multiply
tensor*10

tensor([10, 20, 30])

In [31]:
tensor*tensor # [1*1, 2*2, 3*3]

tensor([1, 4, 9])

In [32]:
# Division
tensor/2

tensor([0.5000, 1.0000, 1.5000])

In [33]:
# Subtraction
tensor - 1

tensor([0, 1, 2])

In [34]:
torch.matmul(tensor, tensor) # 1*1 + 2*2 + 3*3 = 14 : scalar

tensor(14)

### Finding min, max, mean, sum and etc. (aggregation)

In [35]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [36]:
# Find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [37]:
# Find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [38]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [39]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Positional min/max (argmin, argmax)

In [40]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
# Index of minimum value within the x
x.argmin()

tensor(0)

In [42]:
# Index of maximum value within the x
x.argmax()

tensor(9)

### Reshaping, vieweing, stacking, squeezing and unsqueezing

* **Reshaping** - reshapes an input tensor to a defined shape
* **View** - return a view of an input tensor of a certain shape but keep the same memory as the original tensor
* **Stacking** - combine multuple tensor on top of each other or side by side (concatenate)
* **Squeeze** - removes all `1` dimensions from a target tensor
* **Unsqueeze** - add `1` dimension to a target tenso`
* **Permute** - return a view of the input with dimensions permuted (swapped) in a certain way



In [43]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [44]:
# Reshape to (9,1)
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [45]:
# Reshape to (3, 3)
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [46]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [47]:
# Changing z changes x (because it is only a view of x and they share the same memory)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [48]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x ], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [49]:
# Squeezing removes the dimensions
x_orig = torch.arange(1,10).reshape(1,9)
x_squeezed = x_orig.squeeze()
x_orig, x_squeezed

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [50]:
x_squeezed.unsqueeze(dim=0)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [51]:
# Permuting - rearranges dimensions in a specified order (but shares the same memory)
x_image = torch.rand(size=(224,224,3)) # height, width, channels
x_image_permuted = x_image.permute(2,0,1) # channels, height, width
x_image.shape, x_image_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### Selecting data (indexing)
Similar to NumPy

In [52]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [53]:
x[0] # dim = 0

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
x[0][0] # dim = 1

tensor([1, 2, 3])

In [55]:
x[0][0][0] # dim = 2

tensor(1)

In [56]:
# Get all values of the 0th dimension but only index 0 of the 2nd dimension
x[:,0]

tensor([[1, 2, 3]])

In [57]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [58]:
x[:,1,1], x[0, 1, 1]

(tensor([5]), tensor(5))

### PyTorch tensors and NumPy

PyTorch is compatible with NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [59]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [60]:
# Default dtype in NumPy is float64, not float32 as in PyTorch
array.dtype

dtype('float64')

In [61]:
# Change values in array, what will happen to tensor?
# 1) If reassignment -> "array" is allocated on different memory
# and "tensor" keeps a reference to an old memory location of "array"
# 2) If using In-Place operation "+=", then current memory location is udpated
# and "tensor will be updated"

# Case 2:
array += 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [62]:
# Case 1:
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [63]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [64]:
numpy_tensor.dtype

dtype('float32')

### Reproducibility (trying to take random out of random)

To reduce randomness there is a concept of **random seed**

In [65]:
# Create 2 random tensors
rand_tens_A = torch.rand(3,4)
rand_tens_B = torch.rand(3,4)

print(rand_tens_A)
print(rand_tens_B)
print(rand_tens_A == rand_tens_B)

tensor([[0.3740, 0.5225, 0.3822, 0.3395],
        [0.3732, 0.0865, 0.7625, 0.5275],
        [0.9015, 0.3708, 0.8084, 0.7901]])
tensor([[0.9815, 0.2010, 0.6694, 0.7527],
        [0.2643, 0.6126, 0.6746, 0.2270],
        [0.6714, 0.7738, 0.6120, 0.6131]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [66]:
# Let's make some random but reproducible tensors
# Set seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_tens_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED) # we need to set seed every time we call torch.rand()
rand_tens_D = torch.rand(3,4)
print(rand_tens_C)
print(rand_tens_D)
print(rand_tens_C == rand_tens_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Accessing GPU
Running NN is faster on GPU

Options:
1. Use Google Colab GPU (free or subscription)
2. Buy GPU for DL
3. Use cloud computing options

Option 2 and 3 need some setup with PyTorch

In [68]:
# Code for checking GPU availability
torch.cuda.is_available()

True

In [74]:
# Check GPU that is used
!nvidia-smi

Fri Jul 12 16:03:51 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [75]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [76]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors and models on GPU

In [77]:
# Create a tensor
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [79]:
# Move tensor to GPU if available (else CPU)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [81]:
# If calculation is using numpy, then use CPU (can't use transformation)
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])